name: 'Create JIRA ticket'
description: Create JIRA ticket based on the fetched GitHub issue

inputs:
  issue:
    description: >
      Issue to be created in JIRA
    required: true
  # JIRA related inputs
  JIRA_TOKEN: # JIRA token for making api calls
    description: >
      Github secret for the JIRA token for external access
    required: true
  JIRA_PROJECT_ID: #
    description: >
      The project id for Jira
    required: true
    default: '10506'
  JIRA_PROJECT_NAME: #
    description: >
      The project key for Jira
    required: true
    default: UX
  JIRA_URI:
    description: >
      The Jira URI used for the REST API to make the requests to
    required: true
    default: jiradev.bmc.com
  ISSUE_TYPE:
    description: >
      The type of the issue to be used while searching for existing issues.
      This is needed in order to avoid duplicating already raised issues
    required: true
    default: ''
  EXTRA_JIRA_FIELDS:
    description: >
      Provide the extra fields you need to include in the payload sent to Jira during an issue creation
    required: false
    default: ''


outputs:
  http-response:
    description: >
      HTTP response for POST request on JIRA ticket creation

runs:
  using: 'node16'
  main: 'dist/index.js'
